name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.2.4
  - numpy=1.21.2
  - libsndfile
  - pip:
    - soundfile==0.12.1
    - resampy
    - scipy
    - scikit-image
    - torch==2.0.1
    - torchvision==0.15.2
    - opencv-python-headless==4.7.0.72
    - tensorboardX==2.6.1
    - matplotlib==3.5.2