global using Microsoft.Azure.Cosmos;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json.Linq;
global using OrcaHello.Web.Shared.Models.Comments;
global using OrcaHello.Web.Shared.Models.Metrics;
global using OrcaHello.Web.Shared.Models.Tags;
global using Swashbuckle.AspNetCore.Annotations;
global using System.Diagnostics.CodeAnalysis;
global using System.Net;